---
driver:
  name: ec2
  aws_ssh_key_id: YOUR_KEY
  security_group_ids: ['default', 'launch-wizard-1']
  instance_type: t2.micro
  region: us-east-1
  availability_zone: c

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04
    driver:
      image_id: <ami-id> 

suites:
  - name: default
    run_list:
      - recipe[mynginx]

transport:
 ssh_key: PATH/TO/YOUR_KEY
