Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/ubuntu-16.04"
  c.vm.hostname = "default-ubuntu-1604.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/vinodhini.ravikumar/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-cookbooks-default-ubuntu-1604-ac189eb9-1441-41c9-a9a5-5f0574d439cf"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
