Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/ubuntu-16.04"
  c.vm.hostname = "default-ubuntu-1604.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/vinodhini.ravikumar/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-vagrant-cheftest-default-ubuntu-1604-2a770bc6-823b-46e9-a6c1-7774a398c4a4"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
