Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-8"
  c.vm.hostname = "default-centos-8.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/vinodhini.ravikumar/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-mynginx-default-centos-8-969bdc43-d75a-4db1-8f31-a4de19b58291"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
